### ISSUE TITLE
Question 9 - wording could use improvement

### ISSUE THREAD

**Issue by rabbit-pajamas** [learn-co-curriculum/javascript-objects-and-arrays-quiz#10]
The way that question 9 is worded makes it seem as though we are trying to add the string "beta" to the index of 1 within the array. This is due to the wording of, "result(s) in the array," which make it seem as though we are trying to produce the second array shown in this question. I think clearer re-wording would fix any potential confusion, and make it clearer that we are supposed to produce the end result of the letters array listed at the beginning of the question by way of the slice() method.

> Given the array const letters = ["alpha", "gamma", "delta"], which operation(s) result(s) in the array ["alpha", "beta", "gamma", "delta"]?

**Comment by gj** [comment]
Thanks @rabbit-pajamas !
