### ISSUE TITLE
Javascript Arrays and Object Quiz

### ISSUE THREAD

**Issue by sharowynn** [learn-co-curriculum/javascript-objects-and-arrays-quiz#15]
Question 9) "Given the array const letters = ["alpha", "gamma", "delta"], which operation(s) result(s) in the array ["alpha", "beta", "gamma", "delta"]? 

States that [...letters.slice(0, 1), 'beta', ...letters.slice(1)] is the correct answer, but I obtained the correct answer by using [letters.splice(1, 0, 'beta')], as evidenced from the code copied below from the console.

const letters = ["alpha", "gamma", "delta"];
undefined
letters.splice(1, 0, 'beta')

letters
(4) ["alpha", "beta", "gamma", "delta"]

**Comment by gj** [comment]
Thanks @sharowynn !
