### ISSUE TITLE
Javascript Objects And Arrays Quiz

### ISSUE THREAD

**Issue by yunglleung1** [learn-co-curriculum/javascript-objects-and-arrays-quiz#16]
For question 8, "What is the result of the following code in a browser that supports the spread operator?" 
const oneTwoThree = [1, 2, 3]
const sevenEightNine = [7, 8, 9]
[4, 5, 6, ...oneTwoThree, ...sevenEightNine]

Using the spread operator as such "[4, 5, 6, ...oneTwoThree, ...sevenEightNine]" returns a syntax error.  Either the correct answer to the question is "Error" or a new array has to be be created (i.e.: var newArray = [4, 5, 6, ...oneTwoThree, ...sevenEightNine]).

**Comment by gj** [comment]
Not sure where the syntax error is coming from, but it looks fine to me:

<img width="544" alt="screen shot 2017-07-19 at 18 19 36" src="https://user-images.githubusercontent.com/17556281/28392215-fdc28d58-6cae-11e7-8c8b-5201229062b4.png">
