### ISSUE TITLE
Javascript Objects And Arrays Quiz

### ISSUE THREAD

**Issue by yunglleung1** [learn-co-curriculum/javascript-objects-and-arrays-quiz#17]
For question 9, "Given the array const letters = ["alpha", "gamma", "delta"], which operation(s) return the array ["alpha", "beta", "gamma", "delta"]?"

The answer of "[...letters.slice(0, 1), 'beta', ...letters.slice(1)]" returns a syntax error.  A new array has to be created to capture what it returns (i.e.: var newArray = [...letters.slice(0, 1), 'beta', ...letters.slice(1)].

**Comment by gj** [comment]
Not sure where this syntax error is coming from either, but it's working for me:

<img width="452" alt="screen shot 2017-07-19 at 18 22 51" src="https://user-images.githubusercontent.com/17556281/28392313-60da473c-6caf-11e7-8e11-470bde8486b6.png">
