### ISSUE TITLE
My correct answer is marked as incorrect.

### ISSUE THREAD

**Issue by harrychopra** [learn-co-curriculum/javascript-objects-and-arrays-quiz#23]
**Question**: What is the result of the following code in a browser that supports the spread operator?
```
const oneTwoThree = [1, 2, 3]
const sevenEightNine = [7, 8, 9]
[4, 5, 6, ...oneTwoThree, ...sevenEightNine]
 ```
**Choices**:
```
A: [4, 5, 6, 7, 8, 9, 1, 2, 3]
B: [4, 5, 6, 1, 2, 3, 7, 8, 9]
C: [1, 2, 3, 4, 5, 6, 7, 8, 9]
D: Error
```
Isn't the correct answer **D**?  ```[4, 5, 6, ...oneTwoThree, ...sevenEightNine]``` is syntactically incorrect. It isn't an instruction. Why should it return anything?

**Comment by HarryChopra** [comment]
Facepalm moment. Just noticed the question is asking for result in the **browser**.  Quiz is right, The answer is B. Console is nothing but a REPL.
