### ISSUE TITLE
Question #9 is unclear

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/javascript-objects-and-arrays-quiz#4]
Question #9 asks:

> Given the array `const letters = ["alpha", "gamma", "delta"]`, which operation(s) result(s) in the array `["alpha", "beta", "gamma", "delta"]`?

The following two answers correctly modify the array:

`[...letters.slice(0, 1), 'beta', ...letters.slice(1)]`
`letters.splice(1, 0, 'beta')`

The former returns the modified array, while the latter returns an empty array. Checking the value of `letters` after running the second code snippet returns the correctly modified array.

Even though both answers modify the array, only the first answer is accepted as correct. I believe a clearer word than "result" is called for here — we should clarify whether we want the answer to merely _modify_ the array, or to also _return_ the modified array.

Reported by Sarah P (@TheOriginalDollarStoreBaller).

**Comment by rTfact** [comment]
Opened the Lesson for editing and both answers has an 'x' - so they should both be accepted, but the 5th is still not accepted. Something seems to be off.

**Comment by kwebster2** [comment]
@avidor FYI - this is still an issue. Encountered it this morning with a bootcamp prep student.

**Comment by gj** [comment]
Thanks @ivalentine !
