### ISSUE TITLE
Question 5: error

### ISSUE THREAD

**Issue by lisaychuang** [learn-co-curriculum/javascript-objects-and-arrays-quiz#9]
Hi Learn team,

For Q5: What happens to the array in the following code snippet?
```
const dogs = ["Fido", "Odie", "Oscar"]
 
dogs.length
 
dogs.length = 1
```
The answer was: The array becomes just [Fido].

For this to be true, the code should be:
```
const dogs = ["Fido", "Odie", "Oscar"]
  
dogs.slice(0,1)= 1
```

Please review and advise.

Thanks!
Lisa

**Comment by JessRudder** [comment]
Hi @lisaychuang if you run the code as given, it does result in ["Fido"]

```javascript
const dogs = ["Fido", "Odie", "Oscar"]
dogs.length
dogs.length = 1
dogs // ["Fido"]
```
